---
# tasks file for add_all_nodes_to_etc_hosts

- name: "Make sure all hosts are added to each nodes /etc/hosts"
  blockinfile:
    path: "/etc/hosts"
    block: |
      {{ hostvars[item]['external_ip'] | default( hostvars[item]['ansible_default_ipv4']['address'] ) }} {{ item }} {{ item }}.{{ domain_name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_items: "{{ groups[group_name] }}"
